version: '2'

services:

  server:
    build: .
    image: libcore
    container_name: "libcore-server"
    hostname: libdom
    command: ['bin/build-bundle.sh', 'server']

    volumes:
     - ./bin:/opt/app/bin:ro
     - .:/opt/app-source:ro

    ports:
     - "3000:3000"
    
    networks:
     - libcore

  test:
    image: libcore
    container_name: "libcore-test"
    hostname: libdom
    command: ['bin/build-bundle.sh', 'devel-test']

    volumes:
     - ./bin:/opt/app/bin:ro
     - .:/opt/app-source:ro

    networks:
     - libcore
      
  builder:
    image: libcore
    container_name: "libcore-builder"
    command: ['bin/build-bundle.sh', 'build-production']
    
    environment:
     - SOURCE_MOD_PATH=/opt/app-source-modification
  
    volumes:
     - ./bin:/opt/app/bin:ro
     - ./docs:/opt/app/docs
     - ./dist:/opt/app/dist
     - .:/opt/app-source:ro
     - .:/opt/app-source-modification:rw

    networks:
     - libcore

networks:
  libcore:
    driver: bridge
