version: '2'

services:

  server:
    build: .
    image: libcore
    container_name: "libcore-test"
    hostname: libdom
    command: bin/run-devserver.sh

    volumes:
     - .:/opt/app-source:ro

    ports:
      - "3000:3000"
      
  builder:
    image: libcore
    container_name: "libcore-builder"
    command: bin/autosync-builds.sh
    
    environment:
     - SOURCE_MOD_PATH=/opt/app-source-modification
  
    volumes:
      - ./docs:/opt/app/docs
      - ./dist:/opt/app/dist
      - .:/opt/app-source:ro
      - .:/opt/app-source-modification:rw


