version: '2'

services:

  libcore:
    build: .
    image: libcore:latest
    container_name: "libdocore-test"
    hostname: libdom
    command: bin/run-devserver.sh

    volumes:
     - .:/opt/app-source:ro

    ports:
      - "3000:3000"
      
  libcore_builder:
    image: libcore:latest
    container_name: "libcore-builder"
    command: bin/autosync-builds.sh
    
    environment:
     - BUILD_MODE=production
     - SOURCE_MOD_PATH=/opt/app-source-modification
  
    volumes:
      - ./dist:/opt/app/dist
      - .:/opt/app-source:ro
      - .:/opt/app-source-modification:rw


