version: '2'

services:

  server:
    build: .
    image: libcore
    container_name: "libcore-server"
    hostname: libdom
    command: bin/run-devserver.sh

    volumes:
     - ./bin:/opt/app/bin:ro
     - .:/opt/app-source:ro

    ports:
     - "3000:3000"

  test:
    image: libcore
    container_name: "libcore-test"
    hostname: libdom
    command: ['bin/build-bundle.sh', 'devel-test']

    volumes:
     - ./bin:/opt/app/bin:ro
     - .:/opt/app-source:ro
      
  builder:
    image: libcore
    container_name: "libcore-builder"
    command: bin/autosync-builds.sh
    
    environment:
     - SOURCE_MOD_PATH=/opt/app-source-modification
  
    volumes:
     - ./bin:/opt/app/bin:ro
     - ./docs:/opt/app/docs
     - ./dist:/opt/app/dist
     - .:/opt/app-source:ro
     - .:/opt/app-source-modification:rw


